/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorRegistro;
import Modelo.RegistroDAO;
import javax.swing.JOptionPane;
import Modelo.Validador_Registro;
import static Modelo.Validador_Registro.md5;
import Modelo.hash;

/**
 *
 * @author tux-carlos
 */
public class FromLogin extends javax.swing.JFrame {

    /**
     * Creates new form FromLogin
     */
    public FromLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_Usuario = new javax.swing.JTextField();
        Txt_Password = new javax.swing.JPasswordField();
        Btn_Iniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        Txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_UsuarioActionPerformed(evt);
            }
        });

        Btn_Iniciar.setText("Iniciar Sesion");
        Btn_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(Txt_Usuario)
                    .addComponent(Txt_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(Btn_Iniciar)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_UsuarioActionPerformed

    private void Btn_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IniciarActionPerformed
            FromLogin ViewLogin = new FromLogin();
            RegistroDAO ModelRegistro = new RegistroDAO();
            hash ModelHast = new hash();
            Validador_Registro ModelValidador = new Validador_Registro();
            String identificacion = Txt_Usuario.getText();
            char[] pass_word = Txt_Password.getPassword();
            String password = new String (Txt_Password.getPassword());
            boolean vacio_identificacion = ModelValidador.Validar_Campos_Vacios(identificacion);
            boolean vacio_password = ModelValidador.Validar_Campos_Vacios(password);
           
            int num_registros_identficacion = ModelRegistro.ExisteUsuario(identificacion);
            String PassworBD = ModelRegistro.PasswordBD(identificacion);
            boolean Validar_Contraseña = ModelValidador.Contraseña_Valida(password,PassworBD);
              
            boolean Validacion_Vacios= true;
            boolean Validacion_contraseña = true;
            boolean Validacion_Exist_Usuario= true;
            
            if (num_registros_identficacion==0) {
                Validacion_Exist_Usuario= false;
                JOptionPane.showMessageDialog(null, "El usuario no se encuentra registrado en la base de datos" );
            } else {
                Validacion_Exist_Usuario= true;
            }
            
            if (Validar_Contraseña==true) {
                 Validacion_contraseña = true;
            } else {
                Validacion_contraseña =false;
                String micampo2="La contraseña es incorrecta";
                JOptionPane.showMessageDialog(null, micampo2 ); 
            }
            
            if (vacio_identificacion==true  || vacio_password==true) {
                Validacion_Vacios= false;
                String campos = "Existen campos vacios. Por favor diligenciar!";
                JOptionPane.showMessageDialog(null, campos );
            } else {
                Validacion_Vacios= true;
            }
        
            
            if (Validacion_contraseña==true  && Validacion_Vacios==true & Validacion_Exist_Usuario==true) {
               
                FormHome ViewHome = new FormHome();
                ViewHome.setVisible(true);
                ViewHome.setLocationRelativeTo(null);
            } else {
                JOptionPane.showMessageDialog(null, "No se puede completar registro por errores de registro" );
            }
    }//GEN-LAST:event_Btn_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Iniciar;
    public javax.swing.JPasswordField Txt_Password;
    public javax.swing.JTextField Txt_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
