/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.*;
import Vista.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tux-carlos
 */
public class FromRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FromRegistro
     */
    
    public FromRegistro() {
        initComponents();
        TipoUser.removeAllItems();
        RegistroDAO registros = new RegistroDAO();
        ArrayList<String> Lista = new  ArrayList<String>();
        Lista = registros.listTiposUsuarios();
        for (int i = 0; i < Lista.size(); i++) {
            TipoUser.addItem(Lista.get(i));  
        }
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Identificacion");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Fecha");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono");
        modelo.addColumn("Correo");
        modelo.addColumn("TipoUser");
       
        ArrayList<Object[]> ListaRegistros = new ArrayList<Object[]>();
        ListaRegistros = registros.listRegistro();
        for (int i = 0; i <ListaRegistros.size(); i++) {
            modelo.addRow(ListaRegistros.get(i));
        }
        
        jTable2.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tb_identificacion = new javax.swing.JTextField();
        Tb_Nombre = new javax.swing.JTextField();
        Tb_Apellido = new javax.swing.JTextField();
        Tb_FechaNacimiento = new javax.swing.JTextField();
        Tb_Direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tb_Telefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Editar = new javax.swing.JButton();
        Btn_Consultar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Tb_Password = new javax.swing.JPasswordField();
        Tb_Conpassword = new javax.swing.JPasswordField();
        TipoUser = new javax.swing.JComboBox<>();
        Tb_Correo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO Y CONTROL  DE USUARIOS VIDEO TV S.A.");

        jLabel2.setText("Identificacion:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Fecha Nacimiento:");

        jLabel6.setText("Direccion:");

        jLabel7.setText("Telefono:");

        jLabel8.setText("Tipo Usuario:");

        Btn_Nuevo.setText("Nuevo");
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });

        Btn_Editar.setText("Editar");

        Btn_Consultar.setText("Consultar");
        Btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConsultarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setText("Eliminar");

        jLabel9.setText("Correo:");

        jLabel10.setText("contraseña:");

        jLabel11.setText("Confirmar Contraseña:");

        TipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificacicion", "Nombre", "Apellido", "Fecha", "Direccion", "Telefono", "Usuario", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Nuevo)
                                .addGap(42, 42, 42)
                                .addComponent(Btn_Editar)
                                .addGap(43, 43, 43)
                                .addComponent(Btn_Consultar)
                                .addGap(44, 44, 44)
                                .addComponent(Btn_Eliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Tb_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tb_identificacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tb_Apellido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tb_Password)
                                    .addComponent(TipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Tb_Correo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                        .addComponent(Tb_Telefono, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tb_Direccion, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tb_FechaNacimiento, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(Tb_Conpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Tb_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Tb_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Tb_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tb_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Tb_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(Tb_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(6, 6, 6))
                            .addComponent(TipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Tb_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tb_Conpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(Tb_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Nuevo)
                    .addComponent(Btn_Editar)
                    .addComponent(Btn_Consultar)
                    .addComponent(Btn_Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ConsultarActionPerformed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
            FromRegistro ViewRegistro = new FromRegistro();
            RegistroDAO ModelRegistro = new RegistroDAO();
            hash ModelHast = new hash();
            Validador_Registro ModelValidador = new Validador_Registro();
            String identificacion = Tb_identificacion.getText();
            String nombre = Tb_Nombre.getText();
            String apellido = Tb_Apellido.getText();
            String fecha_nac = Tb_FechaNacimiento.getText();
            String direccion = Tb_Direccion.getText();
            String telefono = Tb_Telefono.getText();
            //String tipo_user = ViewRegistro.Tb_TipoUser.getText();
            String tipo_user =(String) TipoUser.getSelectedItem();
            String correo = Tb_Correo.getText();
            JOptionPane.showMessageDialog(null, correo ); 
            char[] pass_word = Tb_Password.getPassword();
            char[] con_pass_word = Tb_Conpassword.getPassword();
            String password = new String (Tb_Password.getPassword());
            String conpassword = new String (Tb_Conpassword.getPassword());
            boolean vacio_identificacion = ModelValidador.Validar_Campos_Vacios(identificacion);
            boolean vacio_nombre = ModelValidador.Validar_Campos_Vacios(nombre);
            boolean vacio_apellido = ModelValidador.Validar_Campos_Vacios(apellido);
            boolean vacio_fecha_nac = ModelValidador.Validar_Campos_Vacios(fecha_nac);
            boolean vacio_direccion = ModelValidador.Validar_Campos_Vacios(direccion);
            boolean vacio_telefono = ModelValidador.Validar_Campos_Vacios(telefono);
            boolean vacio_correo = ModelValidador.Validar_Campos_Vacios(correo);
            boolean vacio_password = ModelValidador.Validar_Campos_Vacios(password);
            boolean vacio_conpassword = ModelValidador.Validar_Campos_Vacios(conpassword);
            String ContraseñaCifrada="";
            
            boolean Validacion_contraseña = true;
            boolean Validacion_Correo= true;
            boolean Validacion_Vacios= true;
            boolean Validacion_Exist_Usuario= true;
            
            int num_registros_identficacion = ModelRegistro.ExisteUsuario(identificacion);
            boolean Confirmar_Contraseña = ModelValidador.Validar_Contraseña(pass_word,con_pass_word);
            if (Confirmar_Contraseña==true) {
                 ContraseñaCifrada=ModelValidador.md5(password);
                 Validacion_contraseña = true;
            } else {
                Validacion_contraseña =false;
                String micampo2="Las contraseñas no coinciden";
                JOptionPane.showMessageDialog(null, micampo2 ); 
            }
            
            boolean ValidarCorreo=ModelValidador.ValidarEmail(correo);
            if (ValidarCorreo) {
                Validacion_Correo= true;
            } else {
                Validacion_Correo= false;
                String micampo2="Correo invalido";
                JOptionPane.showMessageDialog(null, micampo2 );        
            }
            
            Validacion_Correo= true;
            
            if (vacio_identificacion==true  || vacio_nombre==true || vacio_apellido==true || vacio_fecha_nac==true || vacio_direccion==true || vacio_telefono==true || vacio_correo==true || vacio_password==true || vacio_conpassword==true) {
                Validacion_Vacios= false;
                String campos = "Existen campos vacios. Por favor diligenciar!";
                JOptionPane.showMessageDialog(null, campos ); 
            } else {
                Validacion_Vacios= true;
            }
            
            if (num_registros_identficacion==0) {
                Validacion_Exist_Usuario= true;
            } else {
                JOptionPane.showMessageDialog(null, "El usuario ya se encuentra registrado" );
                Validacion_Exist_Usuario= false;
            }
            
            if (Validacion_contraseña==true && Validacion_Correo== true && Validacion_Vacios==true & Validacion_Exist_Usuario==true) {
                
                int foo = ModelRegistro.Tipo_Usuario(tipo_user);
                password= ContraseñaCifrada;
                String rtaRegistro = ModelRegistro.InsertRegistro(identificacion, nombre, apellido, fecha_nac, direccion, telefono, foo, correo, password);
                if (rtaRegistro!=null) {
                    JOptionPane.showMessageDialog(null, rtaRegistro );
                }else {
                    JOptionPane.showMessageDialog(null, "Error de registro" );
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se puede completar registro por errores de registro" );
            }
            RegistroDAO registros = new RegistroDAO();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Identificacion");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Fecha");
            modelo.addColumn("Direccion");
            modelo.addColumn("Telefono");
            modelo.addColumn("Correo");
            modelo.addColumn("TipoUser");
       
            ArrayList<Object[]> ListaRegistros = new ArrayList<Object[]>();
            ListaRegistros = registros.listRegistro();
            for (int i = 0; i <ListaRegistros.size(); i++) {
                modelo.addRow(ListaRegistros.get(i));
            }
        
            jTable2.setModel(modelo);
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int seleccion = jTable2.rowAtPoint(evt.getPoint());
        Tb_identificacion.setText(String.valueOf(jTable2.getValueAt(seleccion, 0)));
        Tb_Nombre.setText(String.valueOf(jTable2.getValueAt(seleccion, 1)));
        Tb_Apellido.setText(String.valueOf(jTable2.getValueAt(seleccion, 2)));
        Tb_FechaNacimiento.setText(String.valueOf(jTable2.getValueAt(seleccion, 3)));
        Tb_Direccion.setText(String.valueOf(jTable2.getValueAt(seleccion, 4)));
        Tb_Telefono.setText(String.valueOf(jTable2.getValueAt(seleccion, 5)));
        Tb_Correo.setText(String.valueOf(jTable2.getValueAt(seleccion, 6)));
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Consultar;
    public javax.swing.JButton Btn_Editar;
    public javax.swing.JButton Btn_Eliminar;
    public javax.swing.JButton Btn_Nuevo;
    public javax.swing.JTextField Tb_Apellido;
    public javax.swing.JPasswordField Tb_Conpassword;
    public javax.swing.JTextField Tb_Correo;
    public javax.swing.JTextField Tb_Direccion;
    public javax.swing.JTextField Tb_FechaNacimiento;
    public javax.swing.JTextField Tb_Nombre;
    public javax.swing.JPasswordField Tb_Password;
    public javax.swing.JTextField Tb_Telefono;
    public javax.swing.JTextField Tb_identificacion;
    public javax.swing.JComboBox<String> TipoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
